---
- name: Create a load balancer
  ec2_elb_lb:
    name: "{{ elb_name }}"
    security_group_name: uninstall-sg
    region: "{{ region }}"
    subnets: []
    purge_subnets: no
    cross_az_load_balancing: yes
    connection_draining_timeout: "{{ elb_connection_draining_timeout }}"
    listeners: "{{ elb_listeners }}"
    stickiness: "{{ elb_stickiness }}"
    health_check: "{{ elb_health_check }}"
    state: present
  register: elb

- name: Add instances to ELB
  ec2_elb:
    region: "{{ region }}"
    ec2_elbs: "{{ elb_name }}"
    instance_id: "{{ item }}"
    wait: yes
    state: present
  with_items: "{{ instance_id_list }}"


