--- #EXTRA VARS FOR CREATING SG
REGION: "us-east-1"
SECURITY_GROUP_RULES:
  - name: uninstall-sg
    description: "This is security group for uninstall testing"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
    
region: "{{ REGION }}"
sg_rules: "{{ SECURITY_GROUP_RULES }}"
